#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V

bspc config border_width	3
bspc config window_gap		8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Border
bspc config normal_border_color		#d79921
bspc config active_border_color		#fabd2f
bspc config focused_border_color	#fb4934

# bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

~/.bin/panel &
